apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-namespace
spec:
  clusterSelector:
    matchLabels:
      env: "pr"
    matchExpressions:
      - key: vendor
        operator: In
        values:
          - rosa
          - aro
          - aks
          - eks
          - ocp
