apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-infra-pr
placementRef:
  name: placement-infra-pr
  kind: Placement
  apiGroup: cluster.open-cluster-management.io
subjects:
  - name: policy-infra-baseline-pr
    kind: Policy
    apiGroup: policy.open-cluster-management.io
