apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-infra-ho
placementRef:
  name: placement-infra-ho
  kind: Placement
  apiGroup: cluster.open-cluster-management.io
subjects:
  - name: policy-infra-baseline-ho
    kind: Policy
    apiGroup: policy.open-cluster-management.io
