nameReference:
  - kind: Policy
    group: policy.open-cluster-management.io
    fieldSpecs:
      - kind: PlacementBinding
        group: policy.open-cluster-management.io
        path: subjects/name
  - kind: PlacementRule
    group: apps.open-cluster-management.io
    fieldSpecs:
      - kind: PlacementBinding
        group: policy.open-cluster-management.io
        path: placementRef/name
