apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - policies/policy-namespace.yaml
  - placement/placement.yaml

# This ensures cross-references between PlacementBinding and Policy/PlacementRule
# get the correct suffixes when rendered.
configurations:
  - kustomizeconfig.yaml
